### ISSUE TITLE
Autoload Error Class 'markroland\Emma' not found

### ISSUE THREAD

**Issue by ericdowell** [markroland/emma#5]
I found that I get this error when trying to reference the Emma class when using psr-4 autoloading.

`Fatal error: Uncaught Error: Class 'markroland\Emma' not found in /folder/reference/file.php`

The issue is created from how this packages sets the namespace in composer.json and how it's referenced in the code. The composer.json file sets the `src` folder as `markroland\Emma`, but then in the `Emma` only sets the namespace as `markroland` instead of `markroland\Emma`.

I would like to fix this issue.

**Comment by markroland** [comment]
I just merged your pull request so I think that should close out this issue. Thanks again for your contribution and your patience.
